"""empty message

Revision ID: 665ecad3a46a
Revises: 
Create Date: 2019-11-03 10:46:06.525584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665ecad3a46a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataSets_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('dataSets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataSets'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configs')
    op.drop_table('datasets')
    # ### end Alembic commands ###
